[package]
name = "waveform-visualizer-wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.15.0"
nannou = "0.19.0"
nannou_audio = "0.19.0"
nannou_egui = "0.19.0"
ringbuf = "0.3.3"
