[package]
name = "static-waveform-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
nannou = "0.19.0"
nannou_audio = "0.19.0"
ringbuf = "0.3.3"
